### ISSUE TITLE
Remove `required` properties

### ISSUE THREAD

**Issue by ehmicky** [ARKHN3B/netlify-plugin-use-env-in-runtime#1]
The `inputs` have a default value, therefore they are not required and `required: true` can be removed.

https://github.com/ARKHN3B/netlify-plugin-use-env-in-runtime/blob/920ded63de5e0d9d9e8805ddb0041faeb730e7db/manifest.yml#L7

**Comment by ARKHN3B** [comment]
Thanks for your feedback 🙂, this is corrected. 

See [correction](https://github.com/ARKHN3B/netlify-plugin-use-env-in-runtime/commit/056e3ed6234dabe505ed6f0f79583e9e55eca5d4).
