### ISSUE TITLE
Remove top-level error handler

### ISSUE THREAD

**Issue by ehmicky** [ARKHN3B/netlify-plugin-use-env-in-runtime#2]
In principle, this plugin should not throw exceptions. 
Therefore, it would be better to remove the top-level `try`/`catch` error handler, to make sure any exception is correctly reported to users as plugin errors instead of user configuration errors.

https://github.com/ARKHN3B/netlify-plugin-use-env-in-runtime/blob/920ded63de5e0d9d9e8805ddb0041faeb730e7db/index.js#L39

**Comment by ARKHN3B** [comment]
Okay, good idea. Thank you for this comment 💯

See [correction](https://github.com/ARKHN3B/netlify-plugin-use-env-in-runtime/commit/020ea90f9fe74b3fe6fd66d2db80b10d4633dfa1).
